// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.WordleHelper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("matchCount")]
        public long MatchCount { get; set; }

        [JsonProperty("suggestions")]
        public string[] Suggestions { get; set; }

        [JsonProperty("filters")]
        public Filters Filters { get; set; }

        [JsonProperty("pattern")]
        public string Pattern { get; set; }
    }

    public partial class Filters
    {
        [JsonProperty("green")]
        public Dictionary<string, string> Green { get; set; }

        [JsonProperty("yellow")]
        public string[] Yellow { get; set; }

        [JsonProperty("gray")]
        public string[] Gray { get; set; }
    }
}
